### ISSUE TITLE
MP3 decoding broken

### ISSUE THREAD

**Issue by Holzhaus** [jaqx0r/pymad#5]
I noticed that this package seems to be broken. I wrote a minimal test program:

``` python
#!/usr/bin/env python
import sys
import mad
import wave

if len(sys.argv) not in (2, 3):
    print('Usage: %s INFILE [OUTFILE]' % sys.argv[0])
    sys.exit(1)

mf = mad.MadFile(sys.argv[1])

if len(sys.argv) == 2:
    print('Samplerate: %r' % mf.samplerate())
    print('Mode: %r' % mf.mode())
    print('Channels: %d' % (1 if mf.mode() == mad.MODE_SINGLE_CHANNEL else 2))
else:
    wf = wave.open(sys.argv[2], mode='wb')
    wf.setframerate(mf.samplerate())
    wf.setnchannels(1 if mf.mode() == mad.MODE_SINGLE_CHANNEL else 2)
    #4 is the sample width of 32 bit audio
    wf.setsampwidth(4)
    frame = mf.read()
    while frame is not None:
        wf.writeframes(frame)
        frame = mf.read()
    wf.close()
```

I used the [1938 radio broadcast of "War of the Worlds"](https://ia800201.us.archive.org/1/items/OrsonWellesMrBruns/381030.mp3) to test this.

The output of `MadFile.mode()` is wrong (it's stereo) and conversion to wave produces just noise. Also, the python 3 version returns a samplerate of 0.

```
$ python2 mp3conv.py 381030.mp3
Samplerate: 44100
Mode: 0
Channels: 1

$ python mp3conv.py 381030.mp3
Samplerate: 0
Mode: 0
Channels: 1
```

I'm using the latest available version on Arch Linux: 

```
$ pacman -Qs pymad
local/python-pymad 0.9-1
    Python interface to libmad
local/python2-pymad 0.9-1
    Python interface to libmad
```

**Comment by strayge** [comment]
First part of this script works with python3 if we provide opened file descriptor to MadFile constructor:
```
fi = open(sys.argv[1], 'rb')
mf = mad.MadFile(fi)
```
```
$ python3 pymad_test.py test_cbr128_stereo.mp3
Samplerate: 44100
Mode: 2
Channels: 2

$ python3 pymad_test.py test_vbr8_mono.mp3
Samplerate: 44100
Mode: 0
Channels: 1
```

But there is still only noise in converted wav files.

**Comment by strayge** [comment]
Tried to check [madradio.py](https://github.com/jaqx0r/pymad/blob/master/test/madradio.py) with python2, got 
```
Traceback (most recent call last):
  File "madradio.py", line 51, in <module>
    madradio(url)
  File "madradio.py", line 41, in madradio
    dev.play(buffy, len(buffy))
TypeError: argument 1 must be string or read-only buffer, not bytearray
```
Fixed it by changing type of returned audio data:
`dev.play(buffy, len(buffy))`
changed to 
`dev.play(buffer(buffy), len(buffy))`

But I still hear only noise.  
Is this library working anywhere now?

**Comment by Holzhaus** [comment]
@jaqx0r Any word on this?

**Comment by jaqx0r** [comment]
I haven't been able to test with python 3 anywhere because pyao in Debian
wasn't supported in python 3. It works fine with python2.

If someone can troubleshoot what is wrong and send a PR I will merge it.

**Comment by tgarc** [comment]
conversion is seriously screwed up for me as well. No errors, just erroneously decoded data. I'll try and come up with some example code...

**Comment by petli** [comment]
I ran into this too, using latest pymad with Python 2.7 on a 64-bit Ubuntu 16.04 LTS.

I modified the test/test.py script to output the decoded data to a file:

```python
    #dev = ao.AudioDevice(0, rate=mf.samplerate())
    of = open('foo.raw', 'wb')
    while 1:
        buffy = mf.read()
        if buffy is None:
            break
        of.write(str(buffy))
        #dev.play(buffy, len(buffy))
        # print "current time: %d ms" % mf.current_time()
    of.close()
```

As I understand the documentation that should be PCM, which aplay will play by the format name cdr:

    $ aplay -f cdr foo.raw 
    Playing raw data 'foo.raw' : Signed 16 bit Big Endian, Rate 44100 Hz, Stereo

But this is just noise.  Trying little-endian gives slightly different noise.

**Comment by tgarc** [comment]
yeah it may actually be worth getting this package up to code (zing). this is the only package that addresses MPEG decoding without adding crazy dependencies.

**Comment by petli** [comment]
My guess, though I’m giving up for the night now, is that the mad_fixed_t to int16_t conversion is broken on 64-bit machines.  madplay itself can convert to PCM, so it could be worthwhile to check how it does it.  The alsaplayer code that the pymad conversion uses seems now to be moved into legacy status and haven’t been touched for a long time, so it may have the same issue.

**Comment by jaqx0r** [comment]
Thanks for the updates. I can't repro this yet and I don't use the code
anymore so I rely on and appreciate your debugging.

The 64 bit conversion sounds like a very good theory, thanks.

**Comment by petli** [comment]
Seems to be an issue with the C bytearray API usage and nothing 64-bit related, see PR #9.

**Comment by tgarc** [comment]
@petli Thank you! That fixed it for me.

@jaqx0r
On a related note...maybe instead of continuing to put effort it into this project, it would be more worthwhile to put those efforts into libsndfile? They have started adding mp3 support there (see [this](https://github.com/erikd/libsndfile/issues/258) ticket) albeit with mpg123 (a LGPL licensed library). The advantage is that libsndfile already has the PySoundFile bindings which are pretty actively developed and work cross platform *without* requiring compilation on non-unix platforms. (Full disclosure: I'm a contributor, but mostly just a fan). Just a suggestion, I realize you may have your own reasons for maintaining this library.

**Comment by jaqx0r** [comment]
I wouldn't say I "put effort into this project"... you may have guessed I barely maintain it at the moment, instead relying on the effort of contributors who do.

I fully support anyone who wants to use libsndfile/pysoundfile instead of pymad, I won't get ... *mad*.

My reasons for "maintaining" it: I don't know who still uses it, and so I migrated it to github so that, like this case, if someone found a bug and then someone contributed a fix, it could get out to the users.  It's nearly zero cost to me to have done so.

Thanks to all of you for your time and patience and contributions.
